import Head from "next/head";
import "cal-sans";
import Navbar from "@component/components/ui/Navbar";
import * as Tabs from "@radix-ui/react-tabs";
import { useSession } from "next-auth/react";
import { api } from "@component/utils/api";
import { useRouter } from "next/router";

export default function JourneySlug() {
  const router = useRouter();
  const { data: sessionData } = useSession();

  const { data: timeline } = api.timeline.getTimeline.useQuery(
    router.query.slug as string,
    { enabled: sessionData?.user !== undefined }
  );

  const { mutate: timelineCardMutate } =
    api.timeline.newTimelineCard.useMutation();

    const { data: todo } = api.todo.getTodos.useQuery(
      router.query.slug as string,
      { enabled: sessionData?.user !== undefined }
    );
  
    const { mutate: todoAdd } =
      api.todo.newTodo.useMutation();

  return (
    <>
      <Head>
        <title>Nomad</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col overflow-x-clip">
        <Navbar />
        <div>
          <Tabs.Root>
            <Tabs.List>
              <Tabs.Trigger value="timeline">Timeline</Tabs.Trigger>
              <Tabs.Trigger value="share">Share</Tabs.Trigger>
              <Tabs.Trigger value="todos">Todos</Tabs.Trigger>
              <Tabs.Trigger value="misc">Docs & Misc</Tabs.Trigger>
            </Tabs.List>
            <Tabs.Content value="timeline">
              {JSON.stringify(timeline)}
              <button
                onClick={() => {
                  timelineCardMutate({
                    title: "Eiffel tower",
                    type: "on_going",
                    description: "My summer vacation travel plan",
                    journeyId: String(router.query.slug),
                  });
                }}
              >
                Add info [ test ]
              </button>
            </Tabs.Content>
            <Tabs.Content value="share">Share Goes Here</Tabs.Content>
            <Tabs.Content value="todos">
            {JSON.stringify(todo)}
              <button
                onClick={() => {
                  todoAdd({
                    text: "my todo card 1",
                    journeyId: String(router.query.slug),
                  });
                }}
              >
                Add info [ test ]
              </button>
            </Tabs.Content>
            <Tabs.Content value="misc">Misc Goes Here</Tabs.Content>
          </Tabs.Root>
        </div>
      </main>
    </>
  );
}
