import Head from "next/head";
import Image from "next/image";
import "cal-sans";
import Navbar from "@component/components/Navbar";
import * as Tabs from "@radix-ui/react-tabs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nomad</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col overflow-x-clip">
        <Navbar />
        <div>
          <Tabs.Root>
            <Tabs.List>
              <Tabs.Trigger value="timeline">Timeline</Tabs.Trigger>
              <Tabs.Trigger value="share">Share</Tabs.Trigger>
              <Tabs.Trigger value="todos">Todos</Tabs.Trigger>
              <Tabs.Trigger value="misc">Docs & Misc</Tabs.Trigger>
            </Tabs.List>
            <Tabs.Content value="timeline">Timeline Goes Here</Tabs.Content>
            <Tabs.Content value="share">Share Goes Here</Tabs.Content>
            <Tabs.Content value="todos">Todos Go Here</Tabs.Content>
            <Tabs.Content value="misc">Misc Goes Here</Tabs.Content>
          </Tabs.Root>
        </div>
      </main>
    </>
  );
}
