import Head from "next/head";
import Image from "next/image";
import "cal-sans";
import Navbar from "@component/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nomad</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col overflow-x-clip">
        <Navbar />
      </main>
    </>
  );
}
